#############################################################################
## Server configuration
#############################################################################
server:
  port: ${PORT:3001}

